language: r
sudo: false
cache:
  packages: true
  directories:
  - $HOME/.npm

pandoc_version: 2.1.1

before_install:
  - nvm install stable
  - npm install netlify-cli -g
  - export DEPLOY_MSG="${TRAVIS_COMMIT:0:7} ${TRAVIS_COMMIT_MESSAGE:0:70}"

env:
  - NETLIFY_SITE_ID=2c55589d-0bcd-4f22-b4b7-9580f622f317
  # NETLIFY_AUTH_TOKEN set in travis settings

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

deploy:
  - provider: script
    script: netlify deploy --dir _book --prod --message "$DEPLOY_MSG"
    skip_cleanup: true
    on:
      branch: master